# Generated by Django 5.2.1 on 2025-05-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='id_externo',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
